import { CustomersType } from "../types/CustomersType";

export const demoCustomers: CustomersType[] = [
  {
    id: 1,
    first_name: "John Mwangi",
    last_name: "Nairobi Textiles Ltd",
    email: "john.mwangi@example.com",
    phone: "+254712345678",
    country: "Kenya",
    city: "Nairobi",
    registration_date: "2024-01-01",
  },
  {
    id: 2,
    first_name: "Aisha Hassan",
    last_name: "Mombasa Imports",
    email: "aisha.hassan@example.com",
    phone: "+254723456789",
    country: "Kenya",
    city: "Mombasa",
    registration_date: "2023-11-15",
  },
  {
    id: 3,
    first_name: "David Kimani",
    last_name: "Nakuru Agri-Supplies",
    email: "david.kimani@example.com",
    phone: "+254734567890",
    country: "Kenya",
    city: "Nakuru",
    registration_date: "2024-03-20",
  },
  {
    id: 4,
    first_name: "Fatima Ali",
    last_name: "Kisumu Fish Processors",
    email: "fatima.ali@example.com",
    phone: "+254745678901",
    country: "Kenya",
    city: "Kisumu",
    registration_date: "2023-09-01",
  },
  {
    id: 5,
    first_name: "Peter Ochieng",
    last_name: "Eldoret Timber Merchants",
    email: "peter.ochieng@example.com",
    phone: "+254756789012",
    country: "Kenya",
    city: "Eldoret",
    registration_date: "2024-02-10",
  },
  {
    id: 6,
    first_name: "Grace Wanjiru",
    last_name: "Thika Food & Beverages",
    email: "grace.wanjiru@example.com",
    phone: "+254767890123",
    country: "Kenya",
    city: "Thika",
    registration_date: "2023-12-05",
  },
  {
    id: 7,
    first_name: "Mohammed Said",
    last_name: "Garissa Hardware",
    email: "mohammed.said@example.com",
    phone: "+254778901234",
    country: "Kenya",
    city: "Garissa",
    registration_date: "2024-04-01",
  },
  {
    id: 8,
    first_name: "Sarah Chebet",
    last_name: "Kericho Tea Exporters",
    email: "sarah.chebet@example.com",
    phone: "+254789012345",
    country: "Kenya",
    city: "Kericho",
    registration_date: "2023-10-25",
  },
  {
    id: 9,
    first_name: "James Njoroge",
    last_name: "Nyeri Coffee Growers",
    email: "james.njoroge@example.com",
    phone: "+254790123456",
    country: "Kenya",
    city: "Nyeri",
    registration_date: "2024-01-18",
  },
  {
    id: 10,
    first_name: "Esther Akinyi",
    last_name: "Kakamega Sugar Mills",
    email: "esther.akinyi@example.com",
    phone: "+254701234567",
    country: "Kenya",
    city: "Kakamega",
    registration_date: "2023-08-10",
  },
  {
    id: 11,
    first_name: "Daniel Otieno",
    last_name: "Malindi Tourism Services",
    email: "daniel.otieno@example.com",
    phone: "+254711223344",
    country: "Kenya",
    city: "Malindi",
    registration_date: "2024-03-05",
  },
];