export const demoProducts = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: "$129.99",
    imageSrc: "https://loremflickr.com/100/100/headphones",
    imageAlt: "Wireless Headphones",
    href: "#",
    color: "Black",
    size: "One Size",
  },
  {
    id: 2,
    name: "Smartwatch",
    price: "$199.00",
    imageSrc: "https://loremflickr.com/100/100/watch",
    imageAlt: "Smartwatch",
    href: "#",
    color: "Silver",
    size: "42mm",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    price: "$89.50",
    imageSrc: "https://loremflickr.com/100/100/speaker",
    imageAlt: "Bluetooth Speaker",
    href: "#",
    color: "Blue",
    size: "Medium",
  },
  {
    id: 4,
    name: "Gaming Mouse",
    price: "$59.00",
    imageSrc: "https://loremflickr.com/100/100/mouse,technology",
    imageAlt: "Gaming Mouse",
    href: "#",
    color: "Black/Red",
    size: "Standard",
  },
  {
    id: 5,
    name: "4K Monitor",
    price: "$399.00",
    imageSrc: "https://loremflickr.com/100/100/monitor",
    imageAlt: "4K Monitor",
    href: "#",
    color: "Black",
    size: "27 inch",
  },
  {
    id: 6,
    name: "Mechanical Keyboard",
    price: "$149.00",
    imageSrc: "https://loremflickr.com/100/100/keyboard",
    imageAlt: "Mechanical Keyboard",
    href: "#",
    color: "White",
    size: "Full Size",
  },
  {
    id: 7,
    name: "Laptop Stand",
    price: "$39.99",
    imageSrc: "https://loremflickr.com/100/100/laptop,stand",
    imageAlt: "Laptop Stand",
    href: "#",
    color: "Aluminum",
    size: "Adjustable",
  },
  {
    id: 8,
    name: "USB-C Hub",
    price: "$29.99",
    imageSrc: "https://loremflickr.com/100/100/hub,usb",
    imageAlt: "USB-C Hub",
    href: "#",
    color: "Gray",
    size: "7-in-1",
  },
];
 