export const demoProducts = [
  {
    id: 1,
    name: "Wireless Headphones",
    type: "Electronics",
    price: "KES 129.99",
    item_cost: "KES 85.00",
    status: "in_stock",
    inventory: 78,
    imageSrc: "https://loremflickr.com/100/100/headphones",
    imageAlt: "Wireless Headphones",
    href: "#",
    color: "Black",
    size: "One Size",
    total_order: 584,
  },
  {
    id: 2,
    name: "Smartwatch",
    type: "Electronics",
    price: "KES 199.00",
    item_cost: "KES 132.50",
    status: "low_stock",
    inventory: 12,
    imageSrc: "https://loremflickr.com/100/100/watch",
    imageAlt: "Smartwatch",
    href: "#",
    color: "Silver",
    size: "42mm",
    total_order: 743,
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    type: "Electronics",
    price: "KES 89.50",
    item_cost: "KES 60.00",
    status: "in_stock",
    inventory: 96,
    imageSrc: "https://loremflickr.com/100/100/speaker",
    imageAlt: "Bluetooth Speaker",
    href: "#",
    color: "Blue",
    size: "Medium",
    total_order: 392,
  },
  {
    id: 4,
    name: "Gaming Mouse",
    type: "Electronics",
    price: "KES 59.00",
    item_cost: "KES 39.99",
    status: "out_of_stock",
    inventory: 0,
    imageSrc: "https://loremflickr.com/100/100/mouse,technology",
    imageAlt: "Gaming Mouse",
    href: "#",
    color: "Black/Red",
    size: "Standard",
    total_order: 881,
  },
  {
    id: 5,
    name: "4K Monitor",
    type: "Electronics",
    price: "KES 399.00",
    item_cost: "KES 285.00",
    status: "in_stock",
    inventory: 110,
    imageSrc: "https://loremflickr.com/100/100/monitor",
    imageAlt: "4K Monitor",
    href: "#",
    color: "Black",
    size: "27 inch",
    total_order: 967,
  },
  {
    id: 6,
    name: "Mechanical Keyboard",
    type: "Electronics",
    price: "KES 149.00",
    item_cost: "KES 99.95",
    status: "low_stock",
    inventory: 9,
    imageSrc: "https://loremflickr.com/100/100/keyboard",
    imageAlt: "Mechanical Keyboard",
    href: "#",
    color: "White",
    size: "Full Size",
    total_order: 510,
  },
  {
    id: 7,
    name: "Laptop Stand",
    type: "Electronics",
    price: "KES 39.99",
    item_cost: "KES 21.50",
    status: "in_stock",
    inventory: 67,
    imageSrc: "https://loremflickr.com/100/100/laptop,stand",
    imageAlt: "Laptop Stand",
    href: "#",
    color: "Aluminum",
    size: "Adjustable",
    total_order: 688,
  },
  {
    id: 8,
    name: "USB-C Hub",
    type: "Electronics",
    price: "KES 29.99",
    item_cost: "KES 18.25",
    status: "in_stock",
    inventory: 33,
    imageSrc: "https://loremflickr.com/100/100/hub,usb",
    imageAlt: "USB-C Hub",
    href: "#",
    color: "Gray",
    size: "7-in-1",
    total_order: 312,
  },
];
