import { ProductType } from "../types/ProductType";
export const demoProducts: ProductType[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    unit_price: "KES 129.99",
    status: "in_stock",
    quantity: 78,
    image: "https://loremflickr.com/100/100/headphones",
  },
  {
    id: 2,
    name: "Smartwatch",
    category: "Electronics",
    unit_price: "KES 199.00",
    status: "low_stock",
    quantity: 12,
    image: "https://loremflickr.com/100/100/watch",
  },
  {
    id: 3,
    name: "Mechanical Keyboard",
    category: "Electronics",
    unit_price: "KES 85.50",
    status: "in_stock",
    quantity: 45,
    image: "https://loremflickr.com/100/100/keyboard",
  },
  {
    id: 4,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    unit_price: "KES 59.99",
    status: "in_stock",
    quantity: 60,
    image: "https://loremflickr.com/100/100/speaker",
  },
  {
    id: 5,
    name: "USB-C Hub",
    category: "Accessories",
    unit_price: "KES 35.00",
    status: "in_stock",
    quantity: 110,
    image: "https://loremflickr.com/100/100/usb",
  },
  {
    id: 6,
    name: "Ergonomic Office Chair",
    category: "Home & Office",
    unit_price: "KES 249.99",
    status: "out_of_stock",
    quantity: 0,
    image: "https://loremflickr.com/100/100/chair",
  },
  {
    id: 7,
    name: "Desk Lamp with Wireless Charging",
    category: "Home & Office",
    unit_price: "KES 75.00",
    status: "in_stock",
    quantity: 30,
    image: "https://loremflickr.com/100/100/lamp",
  },
  {
    id: 8,
    name: "Noise-Cancelling Earbuds",
    category: "Electronics",
    unit_price: "KES 150.00",
    status: "in_stock",
    quantity: 90,
    image: "https://loremflickr.com/100/100/earbuds",
  },
  {
    id: 9,
    name: "External Hard Drive 2TB",
    category: "Storage",
    unit_price: "KES 99.00",
    status: "low_stock",
    quantity: 8,
    image: "https://loremflickr.com/100/100/harddrive",
  },
  {
    id: 10,
    name: "Gaming Mouse",
    category: "Electronics",
    unit_price: "KES 45.00",
    status: "in_stock",
    quantity: 55,
    image: "https://loremflickr.com/100/100/gamingmouse",
  },
  {
    id: 11,
    name: "Webcam 1080p",
    category: "Electronics",
    unit_price: "KES 65.00",
    status: "in_stock",
    quantity: 25,
    image: "https://loremflickr.com/100/100/webcam",
  },
  {
    id: 12,
    name: "Smart Home Hub",
    category: "Smart Home",
    unit_price: "KES 110.00",
    status: "in_stock",
    quantity: 40,
    image: "https://loremflickr.com/100/100/smarthome",
  },
];
