import { SalesType } from "../types/SalesType";

export const demoSales: SalesType[] = [
  {
    id: 1,
    items: [
      {
        id: 1,
        name: "Wireless Headphones",
        category: "Electronics",
        unit_price: "KES 129.99",
        status: "in_stock",
        quantity: 78,
        image: "https://loremflickr.com/100/100/headphones",
      },
      {
        id: 3,
        name: "Mechanical Keyboard",
        category: "Electronics",
        unit_price: "KES 85.50",
        status: "in_stock",
        quantity: 45,
        image: "https://loremflickr.com/100/100/keyboard",
      },
    ],
    customer: {
      id: 1,
      first_name: "John",
      last_name: "Mwangi",
      email: "john.mwangi@example.com",
      phone: "+254712345678",
      country: "Kenya",
      city: "Nairobi",
      registration_date: "2024-01-01",
    },
    shipping_address: {
      street: "123 River Road",
      city: "Nairobi",
      state: "Nairobi County",
      country: "Kenya",
      zip_code: "00100",
    },
    status: "completed",
    payment_method: "M-Pesa",
    date: "2024-04-20",
    total_amount: "KES 209.99",
  },
  {
    id: 2,
    items: [
      {
        id: 2,
        name: "Smartwatch",
        category: "Electronics",
        unit_price: "KES 199.00",
        status: "low_stock",
        quantity: 12,
        image: "https://loremflickr.com/100/100/watch",
      },
    ],
    customer: {
      id: 2,
      first_name: "Aisha",
      last_name: "Hassan",
      email: "aisha.hassan@example.com",
      phone: "+254723456789",
      country: "Kenya",
      city: "Mombasa",
      registration_date: "2023-11-15",
    },
    shipping_address: {
      street: "45 Biashara Street",
      city: "Mombasa",
      state: "Mombasa County",
      country: "Kenya",
      zip_code: "80100",
    },
    status: "pending",
    payment_method: "Credit Card",
    date: "2024-05-15",
    total_amount: "KES 199.00",
  },
  {
    id: 3,
    items: [
      {
        id: 4,
        name: "Portable Bluetooth Speaker",
        category: "Electronics",
        unit_price: "KES 59.99",
        status: "in_stock",
        quantity: 60,
        image: "https://loremflickr.com/100/100/speaker",
      },
    ],
    customer: {
      id: 3,
      first_name: "David",
      last_name: "Kimani",
      email: "david.kimani@example.com",
      phone: "+254734567890",
      country: "Kenya",
      city: "Nakuru",
      registration_date: "2024-03-20",
    },
    shipping_address: {
      street: "10 Rift Valley Avenue",
      city: "Nakuru",
      state: "Nakuru County",
      country: "Kenya",
      zip_code: "20100",
    },
    status: "shipped",
    payment_method: "M-Pesa",
    date: "2024-05-18",
    total_amount: "KES 59.99",
  },
  {
    id: 4,
    items: [
      {
        id: 6,
        name: "Ergonomic Office Chair",
        category: "Home & Office",
        unit_price: "KES 249.99",
        status: "out_of_stock",
        quantity: 0,
        image: "https://loremflickr.com/100/100/chair",
      },
      {
        id: 7,
        name: "Desk Lamp with Wireless Charging",
        category: "Home & Office",
        unit_price: "KES 75.00",
        status: "in_stock",
        quantity: 30,
        image: "https://loremflickr.com/100/100/lamp",
      },
    ],
    customer: {
      id: 4,
      first_name: "Fatima",
      last_name: "Ali",
      email: "fatima.ali@example.com",
      phone: "+254745678901",
      country: "Kenya",
      city: "Kisumu",
      registration_date: "2023-09-01",
    },
    shipping_address: {
      street: "23 Lake Road",
      city: "Kisumu",
      state: "Kisumu County",
      country: "Kenya",
      zip_code: "40100",
    },
    status: "completed",
    payment_method: "Bank Transfer",
    date: "2024-04-25",
    total_amount: "KES 324.99",
  },
  {
    id: 5,
    items: [
      {
        id: 9,
        name: "External Hard Drive 2TB",
        category: "Storage",
        unit_price: "KES 99.00",
        status: "low_stock",
        quantity: 8,
        image: "https://loremflickr.com/100/100/harddrive",
      },
      {
        id: 5,
        name: "USB-C Hub",
        category: "Accessories",
        unit_price: "KES 35.00",
        status: "in_stock",
        quantity: 110,
        image: "https://loremflickr.com/100/100/usb",
      },
    ],
    customer: {
      id: 5,
      first_name: "Peter",
      last_name: "Ochieng",
      email: "peter.ochieng@example.com",
      phone: "+254756789012",
      country: "Kenya",
      city: "Eldoret",
      registration_date: "2024-02-10",
    },
    shipping_address: {
      street: "15 Kapsabet Road",
      city: "Eldoret",
      state: "Uasin Gishu County",
      country: "Kenya",
      zip_code: "30100",
    },
    status: "cancelled",
    payment_method: "M-Pesa",
    date: "2024-05-01",
    total_amount: "KES 134.00",
  },
  {
    id: 6,
    items: [
      {
        id: 11,
        name: "Webcam 1080p",
        category: "Electronics",
        unit_price: "KES 65.00",
        status: "in_stock",
        quantity: 25,
        image: "https://loremflickr.com/100/100/webcam",
      },
      {
        id: 10,
        name: "Gaming Mouse",
        category: "Electronics",
        unit_price: "KES 45.00",
        status: "in_stock",
        quantity: 55,
        image: "https://loremflickr.com/100/100/gamingmouse",
      },
      {
        id: 8,
        name: "Noise-Cancelling Earbuds",
        category: "Electronics",
        unit_price: "KES 150.00",
        status: "in_stock",
        quantity: 90,
        image: "https://loremflickr.com/100/100/earbuds",
      },
    ],
    customer: {
      id: 6,
      first_name: "Grace",
      last_name: "Wanjiru",
      email: "grace.wanjiru@example.com",
      phone: "+254767890123",
      country: "Kenya",
      city: "Thika",
      registration_date: "2023-12-05",
    },
    shipping_address: {
      street: "50 Pineapple Street",
      city: "Thika",
      state: "Kiambu County",
      country: "Kenya",
      zip_code: "00100",
    },
    status: "pending",
    payment_method: "Mobile Money",
    date: "2024-05-19",
    total_amount: "KES 260.00", // (65 + 45 + 150)
  },
];