"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { routeMetadata } from "./lib/routeMetadata";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  useEffect(() => {
    const matchedMeta = Object.entries(routeMetadata).find(
      ([route]) => pathname === route || pathname.startsWith(route + "/")
    );

    const meta = matchedMeta?.[1] ?? {
      title: "Sales Dashboard",
      description: "Generated by PawaIT Solutions",
    };

    document.title = meta.title;

    const metaTag = document.querySelector("meta[name='description']");
    if (metaTag) {
      metaTag.setAttribute("content", meta.description);
    } else {
      const newMetaTag = document.createElement("meta");
      newMetaTag.name = "description";
      newMetaTag.content = meta.description;
      document.head.appendChild(newMetaTag);
    }
  }, [pathname]);

  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <Header />
        <div className="flex h-[calc(100vh-64px)]">
          <Sidebar />
          <main className="flex-1 p-6 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
